import React from 'react';
import { Container, Title, Table } from './styles';

const HiraganaTable = () => {
  return (
    <Container>
      <Title>Hiragana</Title>
      <Title>(ひらがな)</Title>
      <Table>
        <thead>
          <tr>
            <th>n</th>
            <th>w-</th>
            <th>r-</th>
            <th>y-</th>
            <th>m-</th>
            <th>h-</th>
            <th>n-</th>
            <th>t-</th>
            <th>s-</th>
            <th>k-</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>ん</td>
            <td>わ</td>
            <td>ら</td>
            <td>や</td>
            <td>ま</td>
            <td>は</td>
            <td>な</td>
            <td>た</td>
            <td>さ</td>
            <td>か</td>
            <td>あ</td>
            <td>
              <strong>a</strong>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td>り</td>
            <td></td>
            <td>み</td>
            <td>ひ</td>
            <td>に</td>
            <td>ち</td>
            <td>し</td>
            <td>き</td>
            <td>い</td>
            <td>
              <strong>i</strong>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td>る</td>
            <td>ゆ</td>
            <td>む</td>
            <td>ふ</td>
            <td>ぬ</td>
            <td>つ</td>
            <td>す</td>
            <td>く</td>
            <td>う</td>
            <td>
              <strong>u</strong>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td>れ</td>
            <td></td>
            <td>め</td>
            <td>へ</td>
            <td>ね</td>
            <td>て</td>
            <td>せ</td>
            <td>け</td>
            <td>え</td>
            <td>
              <strong>e</strong>
            </td>
          </tr>
          <tr>
            <td></td>
            <td>を</td>
            <td>ろ</td>
            <td>よ</td>
            <td>も</td>
            <td>ほ</td>
            <td>の</td>
            <td>と</td>
            <td>そ</td>
            <td>こ</td>
            <td>お</td>
            <td>
              <strong>o</strong>
            </td>
          </tr>
        </tbody>
      </Table>
    </Container>
  );
};

export default HiraganaTable;
